[project]
name = "local-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "notebook>=7.5.0",
    "pandas>=2.3.3",
    "pyyaml>=6.0.3",
    "ruff>=0.14.6",
]
